[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
# [[redirects]]
#   from = "/api/*"
#   to= "/.netlify/functions/:splat"
#   status = 200
# [[plugins]]
#   package = "@netlify/plugin-zip-it-and-ship-it"

# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "no-referrer"
#     Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"